module.exports = {
  image: {
    small: "https://i5.peapod.com/c/X1/X15VG.jpg",
    medium: "https://i5.peapod.com/c/QR/QRWAH.jpg",
    large: "https://i5.peapod.com/c/FM/FMYND.jpg",
    xlarge: "https://i5.peapod.com/c/FC/FC2EZ.jpg"
  },
  nutrition: {
    nutritionShow: true,
    servingSize: "1.0 TBSP",
    servingsPerContainer: "32",
    totalCalories: 100,
    totalCaloriesShow: true,
    fatCalories: 100,
    fatCaloriesShow: true,
    totalFat: 11,
    totalFatShow: true,
    totalFatPct: 17,
    totalFatPctShow: true,
    totalFatUnit: "g",
    saturatedFat: 7,
    saturatedFatShow: true,
    saturatedFatPct: 37,
    saturatedFatPctShow: true,
    saturatedFatUnit: "g",
    transFat: 0,
    transFatUnit: "g",
    transFatShow: true,
    cholesterol: 30,
    cholesterolShow: true,
    cholesterolPct: 10,
    cholesterolPctShow: true,
    cholesterolUnit: "mg",
    sodium: 0,
    sodiumShow: true,
    sodiumPct: 0,
    sodiumPctShow: true,
    sodiumUnit: "mg",
    potassium: 0,
    potassiumShow: false,
    potassiumPct: 0,
    potassiumPctShow: false,
    potassiumUnit: "mg",
    totalCarbs: 0,
    totalCarbsShow: true,
    totalCarbsPct: 0,
    totalCarbsPctShow: true,
    totalCarbsUnit: "g",
    dietaryFiber: 0,
    dietaryFiberShow: true,
    dietaryFiberPct: 0,
    dietaryFiberPctShow: true,
    dietaryFiberUnit: "g",
    sugar: 0,
    sugarUnit: "g",
    sugarShow: false,
    otherCarbs: 0,
    otherCarbsUnit: "g",
    otherCarbsShow: false,
    protein: 0,
    proteinUnit: "g",
    proteinShow: true,
    vitaminAPct: 8,
    vitaminAShow: true,
    vitaminCPct: 0,
    vitaminCShow: false,
    ironPct: 0,
    ironShow: false,
    calciumPct: 0,
    calciumShow: false,
    ww: 3,
    wwShow: true
  },
  flags: {
    sample: false,
    suppressed: false,
    active: true,
    outOfStock: false,
    specialCode: " ",
    upromise: false,
    newArrival: { flag: false, imageURL: "" },
    privateLabel: { flag: false, imageURL: "" },
    preferredItem: { flag: false, imageURL: "" },
    bogo: { flag: false, imageURL: "" },
    sale: { flag: false, imageURL: "" },
    lowPriceEveryday: { flag: false, imageURL: "" },
    organic: { flag: false, imageURL: "" }
  },
  prodId: 3243,
  name: "LAND O LAKES Butter Unsalted Sticks - 4 qrtrs",
  size: "1 LB BOX",
  unitPrice: 6.29,
  unitMeasure: "LB",
  price: 6.29,
  rootCatId: 1834,
  rootCatSeq: 6,
  rootCatName: "Dairy",
  upc: "3450015150",
  hasSubstitute: true,
  substituteId: 187565,
  rating: 0,
  ratingReviewsSuppressed: false,
  marketSpecificReviews: false,
  reviewId: "3243-PPDALL"
};
