FROM node:8.9.1
COPY package.json /code/
WORKDIR /code
RUN npm install
RUN npm install --only=dev
COPY . /code
ENV DATABASE_URL='postgres://postgres@sous-postgres:5432'
CMD npm run start-dev
EXPOSE 8080
